metaplex-foundation/sugar

script/sugar-install.sh

Automated installation script for binary distribution.
Closes #131 
**Note:** Needs testing on an Apple M1 system.

Add automated binary installation script

---

src/config/data.rs
src/create_config/process.rs

Change the date mask from `DD-MM-YYYY` to `YYYY-MM-DD` for date input.

Changed date mask for input

---

src/deploy/process.rs

Removed interruption handler to avoid conflicts during `launch` command.

Removed interruption handler

---

README.md

Couple of changes:
- Added dependencies note
- Formatted the `curl` command in a block to make it easier to be copied

Added dependencies note

---

script/sugar-cli-test.sh

Couple of improvements:
1. Adding the animation url in the `properties.files` on the metadata files
2. There is now an option to run a test with animation files directly

fix(test script): fix animation support

---

.gitignore
Cargo.lock
Cargo.toml

Also adds /.idea to .gitignore to play nicer with intellij

Bump version for hidden settings fix

---

src/config/data.rs

fix(upload): add custom serde name for aws storage

---

Cargo.lock
Cargo.toml
script/sugar-cli-test.sh
src/config/data.rs
src/upload/methods/mod.rs
src/upload/methods/shdw.rs
src/upload/uploader.rs

This PR adds a new `shdw` upload method supporting Shadow Drive v1.5
Closes #225

Add shadow drive support

---

Cargo.lock
Cargo.toml
script/sugar-cli-test.sh
src/upload/methods/aws.rs

Update AWS S3 crate

---

script/sugar-cli-test.sh
src/bundlr/process.rs
src/config/data.rs
src/mint/process.rs
src/upload/methods/bundlr.rs
src/upload/methods/shdw.rs
src/utils.rs
src/verify/process.rs

Support to run sugar against RPC nodes different than devnet/mainnet.

Add unknown cluster type

---

src/create_config/process.rs
src/upload/process.rs
src/validate/format.rs

fix: make symbol optional in validator

---

src/upload/assets.rs

fix(upload): add 'jpeg' to image pattern

---

src/reveal/process.rs

Tweaks the output of the `reveal` command.
- Current output:
- Updated output:

refactor(reveal): formatting output

---

src/verify/process.rs

bug(docs): Fix CM URL cluster param

---

src/validate/process.rs

fix: url in message

---

src/deploy/process.rs
src/upload/assets.rs
src/upload/process.rs

This pull requests implements all of the suggestions from the candy machine audit report by ottersec/Ape16z for the `metaplex-foundation/sugar` repo. A more detailed explanation of the changes in this PR can be found here: https://docsend.com/view/is7963h8tbbvp2g9.
Changes to `src/deploy/process.rs`:
* refactor unnecessary error handling
Changes to` src/upload/assets.rs`:
* remove unused struct definition
* verify that filename arrays contain exactly one element
Changes to `src/upload/process.rs`:
* simplify the logging

Code cleanup

---

src/constants.rs
src/parse.rs
src/reveal/process.rs
src/setup.rs
src/sign/process.rs

Addresses. #347 
Tested `sign` command on devnet and it worked as expected.

fix(reveal,sign): remove GenesysGo rpc urls

---

src/upload/assets.rs

Allow `.mp3` for `animation_url`

---

src/upload/assets.rs

Allow `.glb` for `animation_url`

---

src/upload/assets.rs
src/upload/process.rs

fix(upload): animation link initialization

---

src/upload/process.rs

Sorts the cache items:
- move all non-numeric keys to the beginning and sort alphabetically
- sort numeric keys as integers

Sort cache items

---

src/deploy/process.rs
src/update/process.rs

Adds a warning while updating or creating a candy machine that might potentially be vunerable to bots.

Add warning about bots for vunerable candy machines

---

src/create_config/process.rs

update create-config configurations link in cli output

---

src/airdrop/structs.rs
src/bundlr/process.rs
src/config/data.rs
src/create_config/process.rs
src/deploy/config_lines.rs
src/deploy/process.rs
src/freeze/thaw.rs
src/launch/process.rs
src/main.rs
src/mint/process.rs
src/parse.rs
src/reveal/process.rs
src/show/process.rs
src/sign/process.rs
src/update/process.rs
src/upload/assets.rs
src/upload/methods/bundlr.rs
src/upload/methods/nft_storage.rs
src/upload/methods/pinata.rs
src/upload/process.rs
src/upload/uploader.rs
src/utils.rs
src/validate/parser.rs
src/validate/process.rs
src/verify/process.rs
src/withdraw/process.rs

This change adds a padding the required Bundlr fee amount to fix issues users are having with insufficient Bundlr balance.

update bundlr fee calc to have more padding

---

src/upload/process.rs

Fix comment typo at upload/process.rs

---

Cargo.lock
Cargo.toml
rust-toolchain.toml
src/config/guard_data.rs
src/config/mod.rs
src/guard/show.rs

This PR add the configuration to support Token2022 Payment guard.

Add Token 2022 Payment guard configuration

---

src/upload/assets.rs
src/upload/process.rs

warn when the user sets a creator field in the JSON metadata

---

src/validate/format.rs

keep extra JSON metadata fields

---

.github/workflows/build.yml
script/sugar-cli-test.sh
src/config/data.rs
src/create_config/process.rs
src/upload/methods/sdrive.rs

PR to add sdrive upload method to test script.

Add sdrive to test script

---

src/airdrop/process.rs
src/cli/mod.rs
src/collections/set.rs
src/constants.rs
src/deploy/collection.rs
src/deploy/config_lines.rs
src/deploy/initialize.rs
src/deploy/process.rs
src/freeze/initialize.rs
src/freeze/thaw.rs
src/freeze/unlock_funds.rs
src/guard/add.rs
src/guard/remove.rs
src/guard/update.rs
src/guard/withdraw.rs
src/launch/process.rs
src/main.rs
src/mint/process.rs
src/update/process.rs
src/update/set_token_standard.rs
src/upload/process.rs
src/withdraw/process.rs

This adds priority fees to all transactions. It should be verified that it works (ref discussion on Discord).

Add priority fees

---

Cargo.toml
src/validate/process.rs

link was borked so i fix,
kind regards, 
0xalice

fix broken link
