metaplex-foundation/sugar

src/main.rs

Interrupts any command after a second `Ctrl+C`

Exit on second interruption

---

src/deploy/data.rs
src/deploy/process.rs
src/launch/process.rs
src/main.rs
src/upload/aws.rs
src/upload/bundlr.rs
src/upload/process.rs

Couple of improvements to how `Ctrl+C` interruptions are handled:
- on non-iterative operations, a single `Ctrl+C` will exit the program immediately
- on iterative operations (`upload` and `deploy`), the first `Ctrl+C` signal that the user wants to abort the operation and the command has time to save any data; a second `Ctrl+C` exits the program immediately
The interruption variable was renamed to better reflect its use.

refactor(interruption): handling interruptions in non-iterative operations

---

src/create_config/process.rs

Avoids asking if the number of assets is correct when the `assets` folder is empty:
- Behaviour avoided:

fix(create-config): fix empty assets folder test

---

README.md

Downloading a shell script from github with curl and exectuing it certainly is not best practice. 
It will be the easiest installation method for users new to the terminal.

add description how to curl install the binary with install script

---

src/create_config/process.rs
src/upload/assets.rs

Improves metadata deserialization errors to include more information. Fixes #201 . 
Errors now look like this:
```
samuel@Samuels-MacBook-Pro sugar_test2 % sugar create-config
[1/2] 🍬 Sugar interactive config maker
Check out our Candy Machine config docs to learn about the options:
-> https://docs.metaplex.com/candy-machine-v2/configuration
🛑 Error running command (re-run needed): Failed to read metadata file: assets/0.json with error: missing field `name` at line 34 column 1
```

refactor(create-config, upload): improve serde metadata errors

---

src/upload/assets.rs

Only updates the `uri` for the `properties.files` if there is one to update.
Fixes #202

fix(upload): added size check for files array property

---

src/create_config/process.rs

Displays a message on the terminal when trying to load the `0.json` metadata file, providing more context if an error occurs at this step.
- with error:
- without error:

style(create-config): add message when loading metatada file

---

src/candy_machine.rs
src/create_config/process.rs
src/deploy/process.rs
src/mint/process.rs
src/update/process.rs
src/utils.rs

The following changes have been done
1. Remove WL burn authority / SPL transfer authority delegation (approval and revoke) and instead keep the payer as both
2. Fix a bug of price calculation (where it was 10 ^ 9 even for SPL treasury mode), by creating a parser function
The balance changes are as follows
1. NFT token
2. SPL Treasury Token credit
3. WL token burn 
4. SPL Treasury Token debit
Closes #207

bugfix: Remove placeholder auth delegation

---

.github/workflows/build.yml
script/sugar-install.sh

This PR makes sure to do the following
1. Github Actions (build when tagged) does not bundle the artifacts anymore
2. The install script is changed to download the direct binary instead of fetching the zip and unzipping it later in the commands.
Closes #193

chore: remove artifact zipping in build action

---

src/deploy/process.rs

Not allocating space for config lines when `hiddenSettings` are used.
This PR can only be merged after mpl_candy_machine PR 415 is deployed:
- https://github.com/metaplex-foundation/metaplex-program-library/pull/415

Fixed account size when hiddenSettings are used

---

src/config/data.rs
src/create_config/process.rs
src/upload/bundlr.rs
src/upload/mod.rs
src/upload/nft_storage.rs
src/upload/process.rs

Candy Machine assets can be saved to [nft.storage](https://nft.storage/).
- Add `NftStorage` upload backend
- Store NFT Storage authentication token on sugar config when storage backend selected.
```
[1/4] 🗂  Loading assets
Found 10 image/metadata pair(s), uploading files:
+--------------------+
| images    |     10 |
| metadata  |     10 |
+--------------------+
[2/4] 🖥  Initializing upload
▪▪▪▪▪ Connected
[3/4] 📤 Uploading image files
Sending data: (Ctrl+C to abort)
[00:00:04] Upload successful ███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ 10/10
[4/4] 📤 Uploading metadata files
Sending data: (Ctrl+C to abort)
[00:00:02] Upload successful …
```

NFT Storage as Upload Backend

---

script/sugar-cli-test.sh
src/upload/nft_storage.rs

This PR adds a limit on the number of concurrent uploads for the `nft_storage` method to avoid reaching the rate limit.

Add limit on concurrent uploads

---

Cargo.lock
Cargo.toml
src/main.rs

I tested it on a few commands and the default value of `info` doesn't seem to produce messages (which would interrupt our normal std output). If we find it does we can shift the default level to `error` or turn it off by default.

feat(logging): add solana-logger

---

src/candy_machine.rs
src/cli/mod.rs
src/main.rs
src/show/process.rs

Added `--unminted` flag to `show` command to print and log the list of unminted indices. The list is also logged.

feat(show): add option to show and log unminted indices

---

src/config/data.rs
src/create_config/process.rs
src/deploy/initialize.rs
src/update/process.rs

Prior to this fix there was no way to set go live date to none using sugar. This adds support in the config creator and in the parser

allow none in go live date

---

src/cli/mod.rs

Removes the clap macro. Didn't realize this was possible before
Before: 
```bash
sugar collection set --collection-mint <MintId>
```
After: 
```bash
sugar collection set <MintId>
```

Fix: sugar collection set arguments

---

Cargo.lock
Cargo.toml
src/deploy/process.rs
src/upload/assets.rs
src/upload/methods/bundlr.rs

Updates `bundlr` to v0.2.0 to get away from the OpenSSL requirement and bumps other non-Solana and Metaplex packages.
Closes #176.

chore: update dependencies

---

.github/workflows/build.yml

Enables Windows executable build so I can start testing Sugar on Windows.

chore: enable windows executable build

---

.github/workflows/gh-pages.yml

This PR automates the deploy of `sugar-install.sh` to GitHub pages (`gh-pages` branch).
The install script is available at https://sugar.metaplex.com/install.sh after a successful deploy.

ci(script): deploy install script to gh-pages

---

.github/workflows/gh-pages.yml

Follow up to PR https://github.com/metaplex-foundation/sugar/pull/264
This PR prevents unnecessary github action runs by filtering by file path

ci(script): only run deploy action on file changes

---

src/show/process.rs

Added a message to indicate that all items are minted – the current behaviour just shows a blank line:

fix(show): add message when all items are minted

---

script/sugar-cli-test.sh
src/cli/mod.rs
src/collections/remove.rs
src/collections/set.rs
src/config/data.rs
src/main.rs

This PR moves all the `collection` options to the sub-commands to make usage more intuitive. It also fixes some bugs in the `set` and `remove` commands:
Previously commands were formatted like:
```bash
sugar collection --option1 --option2 set <mint_address>`
```
now they are:
```bash
sugar collection set <mint_address> --option1 --option2
```
Bugs:
* the `cache_option` is shadowed in the candy machine logic so is always `None`
* the `remove` command is messing up the order of the cache items
I'm using the `args.candy_machine` option to detect whether the cache file needs to be updated.
I'm using `shift_remove` to maintain ordering of cache file items.

refactor(collection): fix bugs; move options to subcommand

---

src/errors.rs
src/validate/errors.rs
src/validate/format.rs
src/validate/parser.rs
src/validate/process.rs

Fixes #246 by relaxing the validator to only check for fields specified in our docs.
Refactors `validate` error handling to have a single error vector and write all errors to a `validate_errors.json` file to make it easier for the user to see them (rather than having to dig in the sugar.log file). 
New output error message:
Example `validate_errors.json` file:

refactor(validate): relax validator; simplify error handling and logging

---

src/mint/process.rs

Payer is not always the same as the update authority so we should explicitly use the candy machine update authority in the SetCollectionDuringMint instruction so that other keypairs can mint from a candy machine with the `mint` command.

fix: use correct authority for set collection

---

src/mint/process.rs

Multiple users have run into issues with using invalid whitelist token accounts. Currently the error returned is:
```
AccountNotFound: pubkey=<associated_token_address>
```
This PR provides a more meaningful error:
```
"Uninitialized whitelist token account: {whitelist_token_account}.
Check that you provided a valid SPL token mint for the whitelist."
```
This should be more clear to the user what the issue is and allow them to fix it by checking that they have provided a valid mint address for their whitelist.

fix: improve error for invalid wl token

---

src/sign/process.rs

The current sign command will continue to run if NFTs found. This PR will make it exit early with an error if no NFTs are found for the candy machine.

fix(sign): exit w/ error no NFTs found

---

src/main.rs
src/mint/process.rs

Refactor minting to be async to speed up minting large amounts from the CLI.

refactor: make minting async

---

src/hash/process.rs
src/mint/process.rs

The `mint` command should mint to the keypair calling the command by default, instead of the wallet currently configured in the candy machine wallet.

fix: mint to keypair instead of cm wallet

---

.cargo-husky/hooks/pre-commit
Cargo.lock
Cargo.toml

This PR sets up a custom git hook that will be moved into the .git/hooks directory the first time a clean run of `cargo test` is done. Thereafter, it runs `cargo +nightly fmt`, `cargo clippy` and `cargo test` as a pre-commit hook for git.

ci: cargo-husky and pre-commit git hook

---

Cargo.lock
Cargo.toml
src/pdas.rs

To support sized collections we need `mpl-token-metadata` v1.3.4 which requires the latest version of `mpl-candy-machine`.

chore: bump token-metadata and candy-machine versions

---

src/config/data.rs
src/create_config/process.rs
src/upload/methods/aws.rs

Addresses #322 and #307.
Changes the AWS config option from a single value to a struct:
```Rust
pub struct AwsConfig {
pub bucket: String,
pub profile: String,
pub directory: String,
}
```
This allows the user to set a AWS credentials profile other than `default` to give them more flexibility. In addition, it allows specifying an optional folder name to store the assets in the S3 bucket. If no folder is provided they will be stored at the root level. This lets users store multiple collections in a single bucket.
Finally, this changes the file names to use the standard asset pair file names `0.json, 0.png, 1.json, 1.png` etc. to make it easier to figure out what file is what.

feat: add profile and directory options for aws s3

---

Cargo.lock
Cargo.toml
src/config/data.rs
src/create_config/process.rs
src/deploy/initialize.rs
src/update/process.rs

Addresses #315. 
Adds the `dateparser` library to accept a wide range of date inputs and then converts and stores them as ISO8601 in the UTC timezone.
Changes the EndSetting struct local to Sugar to have both a `Number` and `Date` field to allow storing the date as a string in the config file for consistency.

Feat: Date Parser

---

src/reveal/process.rs

The reveal process was trying to update the collection item and panicking because the index `-1` was outside the u32 bounds. This PR skips the collection index during updates since the collection NFT is not part of the normal reveal process. 
Fixes #328.

fix(reveal): skip collection item during reveal

---

src/collections/remove.rs
src/collections/set.rs

Small tweak to the output of the `set` and `remove` collection commands.
- Current output:
- Updated output:

refactor(set/remove): formatting output

---

src/upload/methods/bundlr.rs
src/upload/uploader.rs

Images and animation URLs will now look like:
```
https://arweave.net/5UnllZT23t5WTqd61Ho4_-J2GxZihEBSdFkZD9d8KI0?ext=png
```
Fixes #303.

refactor(bundlr): add file type to end of image and animation URLs

---

src/constants.rs

https://dev.genesysgo.net is not a valid address and therefore causing issues like this:
`Error running command (re-run needed): error sending request for url (URL): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known`
The correct url is https://devnet.genesysgo.net which I used now.

fix default devnet rpc url

---

src/verify/process.rs

If `num_items` is 0 then we set `step` to `0` instead of `1_000_000 / num_items`
With this PR `sugar verify` works correctly for an empty collection:
```
>>> sugar verify
[1/2] 🍬 Loading candy machine
▪▪▪▪▪ Completed
[2/2] 📝 Verification
Verifying 0 config line(s): (Ctrl+C to abort)
[00:00:00] Config line verification successful █████████████████████████████████████████████████████ 0/0
Verification successful. You're good to go!
See your candy machine at:
-> https://www.solaneyes.com/address/DqfEXKYn8Nct9xaY8A5xj2DUNkwZw8cJKXWS1Wwqt4oK?cluster=devnet
✅ Command successful.
```
Fixes #342

Fix division by zero error when verifying empty collection

---

Cargo.lock
Cargo.toml
src/deploy/collection.rs
src/mint/process.rs

Creates sized collections by default when a collection asset pair is included in the assets directory. There's no real disadvantage I see to everyone having sized collections by default, but if someone really doesn't want a sized collection they can still create the collection parent NFT themselves as unsized and then use the `set-collection` command with Sugar to use it.
Waiting on this feature to be merged and deployed to candy machine devnet to test and finish this PR.

Support Sized Collections

---

script/sugar-cli-test.sh
src/constants.rs
src/validate/errors.rs
src/validate/format.rs
src/validate/parser.rs
src/validate/process.rs

If the `properties.category` field is not set for video, 3d and html nfts, they will not display properly on most wallets and marketplaces.
It [was part of the spec](https://docs.metaplex.com/programs/token-metadata/changelog/v1.0#:~:text=view%20the%20asset.-,properties.category,-%2D%20Supported%20categories%3A), but [seems to have dissapeared](https://docs.metaplex.com/programs/token-metadata/token-standard#:~:text=%5D%2C%0A%20%20%20%20%22-,category,-%22%3A%20%22video).

Fix `properties.category` being silently ignored

---

src/deploy/initialize.rs
src/update/process.rs
src/utils.rs

The `update` command was incorrectly trying to parse decimals from the token account instead of the mint account. This code was duplicated in two places and the bug was only fixed in one. This PR abstracts this code into a helper function to reduce code duplication, and also fixes the bug.

fix: correctly get decimals from mint account

---

src/validate/format.rs

Fixing a typo while running the validate command. The metadata contained the creator address yet it was throwing warning for creator address so, digged a little bit to find out that it was related to category.

Fix typo during the validate cmd

---

Cargo.lock
Cargo.toml
src/freeze/unfreeze_funds.rs

DRAFT: requires `mpl-candy-machine` 4.4 released before merge and needs Cargo.toml file updated to not point to local package.

fix: update unfreeze-funds handler

---

src/upload/assets.rs

Currently Sugar will strip out the `animation_url` from a `json` metadata file if no animation file is found in the assets folder. This PR prevents this, so it is possible to specify an existing animation url directly on the `json` metadata.

fix(upload): allow use of existing animation url

---

.cargo-husky/hooks/pre-commit

Backticks (`` ` ``) are a legacy form of the process substituion syntax (`$()`).
Printing the help message actually runs the command instead.
https://github.com/metaplex-foundation/sugar/blob/996c632535b0ae18057ce1c80edeedd67725ef7a/.cargo-husky/hooks/pre-commit#L10

Fix unintentional running of `cargo fmt`

---

src/deploy/process.rs

Saving the candy machine public key to the cache before sending the deploy transaction allows the cli to automatically detect if the deploy succeeded even if the transaction times out.
Behviour change:
Providing a valid public key that is not a candy machine in the cache results in a warning message and new candy machine being deployed.
The old behaviour was to print the message `Candy machine from cache does't exist on chain!`

Handle transaction timeout during deploy

---

script/sugar-cli-test.sh
src/config/data.rs
src/create_config/process.rs
src/upload/methods/aws.rs

Currently, the `aws` uploader creates URI using the standard AWS domain (`s3.amazonaws.com`). This PR adds an option to specify custom domains.

Add option to specify a custom domain

---

src/mint/process.rs

This fixes the issue of being able to capture signature reading the terminal output programatically.
For example.. today.. if you run a mint and redirect the output with `> output.txt` you loose the signature id because ProgressBar will not print if is redirected or run outside a terminal. This behavior makes it impossible to automate tasks using sugar to mint NFTs and read the output.

print signature mint instead of sending it to ProgressBar

---

.github/workflows/build.yml
Cargo.lock
Cargo.toml
README.md

There's a possibility of a segfault in the time dependency on chrono and we don't actually use it, so this PR removes it.

fix: remove chrono time dep

---

.github/workflows/build.yml

#379 accidentally removed the `pull_request` trigger for the workflow.
This adds back the trigger to allow pull requests to be built and test.

Run CI workflow on pull requests

---

Cargo.lock
Cargo.toml
src/deploy/collection.rs
src/freeze/mod.rs
src/mint/process.rs
src/utils.rs
src/withdraw/process.rs

This PR upgrades Anchor to 0.25 and Solana 1.10 to support programs that do reallocating of account size.

chore: bump Anchor and Solana versions

---

.github/workflows/build.yml
README.md

Fixes the CI so it doesn't run actions twice on pushes to an open PR.

ci: avoid redundant runs

---

src/cli/mod.rs
src/freeze/unfreeze_funds.rs
src/main.rs

The `unfreeze-funds` is missing some additional accounts required to work when SPL token mint is enabled.

fix: add missing accounts to unnlock-funds when token mint enabled

---

src/upload/assets.rs
src/upload/process.rs

This PR changes the upload logic to skip the upload of image and animation files when the metadata contains a complete link.
Closes #300

Use existing image and animation links from metadata

---

src/upload/methods/aws.rs
src/upload/process.rs

Someone triggered this error with a misconfigured cache file, so seems worth replacing the `unwrap` with a proper error. Also fixed a clippy lint.

Replace panic with proper error

---

src/lib.rs
src/main.rs
src/parse.rs
src/upload/methods/bundlr.rs

* Add padding to Bundlr fee calculation
* Fix clippy "needless borrow" lints
* Disable clippy "unlined_format_args" warnings

add padding to bundlr fee calculation; fix clippy lints

---

src/cli/mod.rs
src/deploy/process.rs
src/launch/process.rs
src/main.rs

`sugar deploy` now accepts an optional argument (`--collection-mint <COLLECTION_MINT>`), which allows creating a candymachine without creating a collection.
Fixes #431
Tested with `sugar upload` then `sugar deploy` then `sugar mint`:
1. Define `0.json`/`0.jpg` with no `collection.json`, then, `sugar deploy --collection-mint <COLLECTION_MINT>`, [minted NFT](https://solscan.io/token/AGiG3cssSFkDP6Tn72d1enczvGY98SWdiDUSt6mihtrW?cluster=devnet) (new behavior).
2. Define `0.json`/`0.jpg` with no `collection.json`, create a candymachine with js code and set the output to `cache.json`, works as before.
3. Define `0.json`/`0.jpg` and `collection.json`/`collection.png`, works as before.

Allow an existing collection on "sugar deploy"

---

src/airdrop/process.rs
src/config/data.rs
src/create_config/process.rs
src/validate/process.rs

Addresses #432 in file `airdrop/process.rs`. Other files are clippy lint fixes.

Avoid Airdrop Double Sends

---

Cargo.lock
Cargo.toml
script/sugar-cli-test.sh
src/constants.rs
src/show/process.rs

This PR fixes the display of unminted indices. The current code was using an incorrect offset. Additionally, the presentation of the indices was improves using the `tabled` crate.

Fix unminted indices offset

---

Cargo.lock
Cargo.toml
src/collections/set.rs
src/deploy/collection.rs
src/deploy/initialize.rs
src/freeze/initialize.rs
src/freeze/mod.rs
src/freeze/unlock_funds.rs
src/pdas.rs
src/setup.rs
src/utils.rs
src/withdraw/process.rs

This PR updates the anchor-lang to `0.27.0`, as well as, Candy Guard and Candy Machine Core to `1.0.3`.

Update anchor dependency

---

src/config/data.rs
src/deploy/initialize.rs

Addresses #404. This value is present on Candy Machine's config, so should be exposed by Sugar as well.

add max-edition-supply config value

---

script/sugar-cli-test.sh

PR to fix the variable used to generate the name of the asset when the manual cache option is selected.

Use index variable on name

---

src/config/data.rs
src/create_config/process.rs
src/upload/methods/mod.rs
src/upload/methods/sdrive.rs
src/upload/uploader.rs

Add SDrive as a new backend for upload. Sdrive is a service on top of Shadow Drive that makes effortless to upload images and metadata by providing an API endpoint rather than making the user go to hoops to create a storage account and have SHDW in their wallet.
It requires the user to have an API key from https://sdrive.app and API credits, and this PR makes sure the user is asked for their private key when they set up their mint.
The files are stored on immutable Shadow Drive storage accounts.
I did a test launch
https://www.solaneyes.com/address/ACeieWp9RkUoBZR4dAGTDWPkDJNT5RmMy3TH7VhfDNnE?cluster=devnet
and a test mint
https://solana.fm/address/ChHQTxBEFAhasJR5DgS7jpNaUpcwzi8McMHC2wDW7KG2?cluster=devnet-solana
using the test collection at Metaplex docs.
You need an API key to test …

Adds SDrive as upload backend

---

src/cli/mod.rs
src/create_config/process.rs
src/main.rs
src/upload/assets.rs
src/withdraw/process.rs

Allows listing other user's candy machines by passing `--authority`, useful for debugging.
Fixes the authority offset from 8 to 16 for Candy Machine v3 (replaces #464).
Also fixes clippy warnings.
```console
> sugar withdraw -h
sugar-withdraw
Withdraw funds a from candy machine account closing it
USAGE:
sugar withdraw [OPTIONS]
OPTIONS:
--authority <AUTHORITY>
Address of authority to find candy machines for. If authority != keypair.pubkey then
force --list. Defaults to keypair.pubkey
...
```

feature: Add `--authority` option to `withdraw` subcommand

---

Cargo.lock
Cargo.toml

New builds will fail currently if they don't have a lock file with `mpl-token-auth-rules` 1.3 in it as pulling in `1.4` has issues with solana program and Pubkey not implementing borsh. This patch pins `mpl-token-auth-rules` to 1.3 to fix builds until there's time to do a full upgrade to `mpl-token-auth-rules` 2.0 solana 1.16, etc.
This PR also bumps lock file deps to get security patches.

fix broken build; bump lock deps

---

Cargo.lock
Cargo.toml
src/show/process.rs

After the last merge, which technically just changed some strings, the build was failing.
This fixes it and releases a new 2.6.1 version to have the new developer hub url in the binary.

Fix Build, release 2.6.1

---

.github/workflows/build.yml

Currently no binary for m1 is created. The macos 14 runner is based on m1. By adding it it should be created.

Fix m1 pipeline

---

Cargo.lock
src/config/data.rs
src/deploy/process.rs
src/freeze/thaw.rs
src/main.rs
src/mint/process.rs
src/pdas.rs
src/upload/process.rs

Replacing the overcautious safe_deserialize for TM Metadata accounts with the less safe deserialize. This should not be an issue because ownership and necessary checks are checked on-chain.
Additional changes are added to get the code to properly compile and should have no effect on functionality.

Switching to plain deserialize for TM resize

---

src/cli/mod.rs
src/main.rs
src/reveal/process.rs

Implement `sugar reveal --new-update-authority <public key>` to allow transferring the update authority during the reveal process.

feature: Add flag `--new-update-authority` to the Reveal Command

---

script/sugar-cli-test.sh
src/deploy/process.rs
src/reveal/process.rs

Users try to create CMs with hiddenSettings without reveal, to have everyone mint the same NFT.
This allows it but throws warnings when the cache is incomplete like
sugar deploy
sugar reveal

Allow hiddenSettings with incomplete cache

---

.github/workflows/build.yml

Users reported that both mac binaries since 2.8 are for arm. Looks like github changed the runner behaviour.
https://github.com/actions/runner-images/issues/9741
We need macos-13 for intel based binaries.

fix mac architecture
